# -*- coding: utf-8 -*-
"""Phylogenetic Tress

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d6hDhw3HUyVXxrJCVD-TNCpeYCqCxgMK
"""

!pip install biopython
from Bio import AlignIO
from Bio import Phylo
from Bio.Phylo.TreeConstruction import DistanceCalculator, DistanceTreeConstructor
import matplotlib.pyplot as plt
alignment_file = "alignment.fasta"
from google.colab import files
uploaded=files.upload()
alignment = AlignIO.read("alignment.fasta.txt", "fasta")
calculator = DistanceCalculator('identity')
dm = calculator.get_distance(alignment)
constructor = DistanceTreeConstructor()
tree = constructor.nj(dm)
import matplotlib.pyplot as plt
from Bio.Phylo import draw
name_mapping = {
    "FJ455125.1": "Tiger (Ptt01)",
    "FJ455122.1": "Tiger (Pta02)",
    "FJ461531.2": "Tiger (Pts01)",
    "KF297711.1": "Leopard",
    "KF297710.1": "Jaguar",
    "KF297726.1": "Lion"
}
for terminal in tree.get_terminals():
    if terminal.name in name_mapping:
        terminal.name = name_mapping[terminal.name]
fig = plt.figure(figsize=(10, 8), dpi=300)
axes = fig.add_subplot(1, 1, 1)
Phylo.draw(tree, axes=axes, label_func=lambda x: str(x) if x.is_terminal() else None)